### PR TITLE
Update to Swift 4.1

### PR DESCRIPTION
**Pull request by CodaFi**

### CODE REVIEW

**Comment by mpurland** [comment]
@CodaFi Any progress with this PR? I'm currently getting swiftc crashes for:

```
1.	While emitting IR SIL function @_TF5Basis5delayurFFT_q_GVS_4Lazyq__ for 'delay' at /Users/mpurland/Development/All/git/Basis/Basis/Lazy.swift:24:8
2.	While converting type 'ST<τ_0_0, STRef<τ_0_0, τ_0_0>>' (declared at [/Users/mpurland/Development/All/git/Basis/Basis/ST.swift:12:8 - line:24:1] RangeText="struct ST<S, A> {	
	private let apply : World<RealWorld> -> (World<RealWorld>, A)
	
	init(apply : World<RealWorld> -> (World<RealWorld>, A)) {
		self.apply = apply
	}
	
	// Returns the value after completing all transformations.
	public func runST() -> A {
		let (_, x) = self.apply(realWorld)
		return x
	}
}")
```

**Comment by CodaFi** [comment]
Nope.  We're stucj

**Comment by mpurland** [comment]
When I get some time I'll look into this further. There must be a way around it...I'm optimistic.

**Comment by CodaFi** [comment]
Oh boy... Give it 10 minutes then put it down.  This thing has crashed every version of the swift compiler since 1.2.

**Comment by mpurland** [comment]
It should be a testbed for the Swift Compiler developers... :)

**Comment by CodaFi** [comment]
Another Swift release, another Swift crash 😭.  At least it's in the same place

```
1.  While emitting IR SIL function @_TF5Basis5delayurFFT_xGVS_4Lazyx_ for 'delay' at /Users/cfi/Desktop/Basis/Basis/Lazy.swift:24:8
2.  While converting type 'ST<Wrapped, STRef<Wrapped, Wrapped>>' (declared at [/Users/cfi/Desktop/Basis/Basis/ST.swift:12:8 - line:24:1] RangeText="struct ST<S, A> {   
    fileprivate let apply : (World<RealWorld>) -> (World<RealWorld>, A)

    init(apply : @escaping (World<RealWorld>) -> (World<RealWorld>, A)) {
        self.apply = apply
    }

    // Returns the value after completing all transformations.
    public func runST() -> A {
        let (_, x) = self.apply(realWorld)
        return x
    }
}")
```

**Comment by CodaFi** [comment]
Knocked out 3.2 and 4.0 mode

```
1.	While emitting IR SIL function "@_T05Basis6stToIOAA0D0VyxGAA2STVyAA9RealWorld_pxGlF".
 for 'stToIO(_:)' at /Users/cfi/Desktop/Basis/Basis/ST.swift:170:10
2.	While converting type 'IO<τ_0_0>' (declared at [/Users/cfi/Desktop/Basis/Basis/IO.swift:12:8 - line:24:1] RangeText="struct IO<A> {
	internal let apply : (World<RealWorld>) -> (World<RealWorld>, A)

	init(_ apply : @escaping (World<RealWorld>) -> (World<RealWorld>, A)) {
		self.apply = apply
	}

	// The infamous "back door" to the IO Monad.  Forces strict evaluation
	// of the IO action and returns a result.
	public func unsafePerformIO() -> A  {
		return self.apply(realWorld).1
	}
}")
```

**Pull request closed without merging**
